# Generated by Django 4.0.5 on 2022-07-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='job', max_length=50),
            preserve_default=False,
        ),
    ]
